version: '2'
services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - ${RABBITMQ_AMQP_EXTERNAL_PORT}:${RABBITMQ_AMQP_PORT}
      - ${RABBITMQ_MANAGEMENT_EXTERNAL_PORT}:${RABBITMQ_MANAGEMENT_PORT}
      - ${RABBITMQ_WEBSOCKET_PORT_EXTERNAL}:15675
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  messaging:
    build: ./java/messaging
    environment:
      TOPIC_SENSORS: ${TOPIC_SENSORS}
      TOPIC_SMART_DEVICES: ${TOPIC_SMART_DEVICES}
      RABBITMQ_AMQP_HOST: rabbitmq
      RABBITMQ_AMQP_PORT: ${RABBITMQ_AMQP_PORT}
      RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASS: ${RABBITMQ_DEFAULT_PASS}
  
  nginx:
    build: ./client/nginx/
    ports:
      - ${CLIENT_HTTP_PORT}:80
      - ${CLIENT_HTTPS_PORT}:443
    volumes:
      - ./client/public:/app/public
      - ./client/nginx/nginx.conf:/etc/nginx/nginx.conf

  vite:
    image: node:19-alpine
    command: sh -c "npm install ; npm run dev -- --https"
    volumes:
      - ./client/:/app
    working_dir: /app
    ports:
      - ${VITE_SERVER_PORT}:5137
    environment:
      VITE_TOPIC_SENSORS: ${TOPIC_SENSORS}
      VITE_TOPIC_SMART_DEVICES: ${TOPIC_SMART_DEVICES}
      VITE_WEBSOCKET_URL: ws://127.0.0.1:${RABBITMQ_WEBSOCKET_PORT_EXTERNAL}/ws