version: '2'
services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - ${RABBITMQ_AMQP_EXTERNAL_PORT}:${RABBITMQ_AMQP_PORT}
      - ${RABBITMQ_MANAGEMENT_EXTERNAL_PORT}:${RABBITMQ_MANAGEMENT_PORT}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  messaging:
    build: ./java/messaging
    environment:
      TOPIC_SENSORS: ${TOPIC_SENSORS}
      TOPIC_SMART_DEVICES: ${TOPIC_SMART_DEVICES}
      RABBITMQ_AMQP_HOST: rabbitmq
      RABBITMQ_AMQP_PORT: ${RABBITMQ_AMQP_PORT}
      RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASS: ${RABBITMQ_DEFAULT_PASS}